# Vanilla Neural Network
I think this question is less convenient to tackle using vanilla neural network than using sequential models like RNN, LSTM, etc. This is because vanilla NN normally deals with input with **fixed length**. To accomodate our need of different length from `2` to `10`, we would have to train `9` models, each with input shape `2, 3, 4, ...`.

**Note**. Creating `10-2+1 = 9` NNs is not a bad thing. Their cooperated performance might also not mediocre. It is just that I find it more challenging/rewarding to try to find a devise-once-use-everywhere solution, so I ended up spending most of the time on finding such solutions. 

## Correction
Actually, there exist ways to still use vanilla NN for this question. One such way is through padding. More precisely, let's take a few examples to illustrate our point:

01. Input array `[0, 9, 7, 1, 2]`
  - We may use integers $\in {91, 92, 93, \ldots, 98}$ to pad, whence the padded input array becomes
  `[0, 9, 7, 1, 2, 91, 92, 93, 94, 95]`. We always pad until the padded array has length `10`.
  - As for the corresponding output, I choose to return the permutation which make the padded input array sorted.
  In this particular example,  that would be `[0, 3, 4, 2, 1, 5, 6, 7, 8, 9]`. Note how the last five indices
  have not been altered at all in this permutation.
02. Input array `[9, 0]`
  - The padded input array would be `[9, 0, 91, 92, 93, 94, 95, 96, 97, 98]`.
  - The output would be `[1, 0, 2, 3, 4, 5, 6, 7, 8, 9]`.

This looks a little involved and artificial; nevertheless, it also brings convenience

- The input and output are now both of fixed shape
- The fact of being of fixed shape makes creating the dataset a lot more easier, (which in turn makes splitting it into Train/Validation/Test sets easier).

### Correction inside correction
We have said that we wanted to use `91..98` as padders, but, sorry, because normally we would use one-hot encoding during the dataset preparation for `X`. It's clueless how these `91..98` should be mapped. So, let's just forget the `91..98` idea, just **pad with zero vectors**.

In [1]:
padders = list(range(91, 98+1))
padders

[91, 92, 93, 94, 95, 96, 97, 98]

In [2]:
import tensorflow as tf
import tensorflow.keras as keras
import numpy as np
from functools import reduce
from itertools import combinations, permutations
from math import factorial

In [3]:
tf.math.softmax([[0.4, 0], [0.1, 0.2]]).numpy()

array([[0.59868765, 0.40131232],
       [0.4750208 , 0.5249792 ]], dtype=float32)

In [4]:
A = np.arange(2*7).reshape((2,7))
A[:, [3,5]], A

(array([[ 3,  5],
        [10, 12]]),
 array([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]]))

In [5]:
np.argmax(tf.math.softmax([[0.4, 0, 0.1], [0.1, 0.2, 0.1]]).numpy(), axis=1)

array([0, 1])

The following `X` will be our dataset (including training/validation/test sets).

In [6]:
n_classes = 10
max_length = 10
n_instances = sum([reduce(lambda x, y: x*y, range(n_classes,n_classes-length,-1)) for length in range(2, max_length+1)])
n_instances

9864090

In [7]:
X = np.zeros((n_instances, max_length, n_classes), dtype=np.float32)

I have said in `README.md` that CNN is of little use here because we are not dealing with images. However, the shape of `X` does look like a single-channel image. Still, using CNN to extract local features makes little sense, so we will probably stick to our plan -- Maybe the first layer of our vanilla NN would be a `keras.layers.Flatten` and followed by a few fully connected layers.

In [8]:
np.argsort([9,5,0,3])

array([2, 3, 1, 0])

In [9]:
A = np.array([9,5,0,3])
A[np.argsort(A)]

array([0, 3, 5, 9])

In [10]:
def one_hot(array, depth=n_classes):
    """
    array is an ndarray of shape (None,)
    """
    return np.eye(depth)[array, :]

In [11]:
one_hot(A)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [12]:
tf.one_hot(A, depth=10)

<tf.Tensor: shape=(4, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.]], dtype=float32)>

In [13]:
# labels
Y = np.empty((n_instances, max_length), dtype=np.float32)  

In [14]:
np.concatenate(([1,2,3], [4,5,6]))

array([1, 2, 3, 4, 5, 6])

In [15]:
p = (4,3,9,7,8)
length = len(p)
np.concatenate((np.argsort(p), np.arange(length, max_length)))

array([1, 0, 3, 4, 2, 5, 6, 7, 8, 9])

**(?)** Improvement. The above construction of `X, Y` takes a little long (6min on Thinkpad X200), can consider using concurrent programming.

In [16]:
X[...] = 0
X.shape, X.dtype

((9864090, 10, 10), dtype('float32'))

In [17]:
import concurrent.futures

In [22]:
%%time
#X[...] = 0
lengths = list(range(2, max_length+1))
S = set(range(0, 9+1))

def fill_X(length, X=X, Y=Y):
    print(f"Processing length={length} ")
    index_instance = sum([reduce(lambda x, y: x*y, range(10,10-l,-1)) for l in range(2, length)])
    print(f"index_instance = {index_instance}")
    for c in combinations(S, length):
        for p in permutations(c):
            #print(f"(index_instance/n_instances = {index_instance}/{n_instances})", end="\r")
            #print(f"np.array(p) = {np.array(p)}")
            X[index_instance, :length, :] = one_hot(np.array(p))#[..., np.newaxis]
            Y[index_instance, :] = np.concatenate((np.argsort(p), np.arange(length, max_length)))
            print(f"x = {one_hot(np.array(p))}")
            print(f"y = {Y[index_instance, :]}")
            index_instance += 1
    print(f"Finished length={length} ")

with concurrent.futures.ProcessPoolExecutor() as executor:
    executor.map(fill_X, lengths)

Processing length=2 Processing length=5 Processing length=4 Processing length=3 


index_instance = 810index_instance = 5850
index_instance = 0index_instance = 90



x = [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]x = [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]x = [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]

x = [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]]
y = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]y = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]

y = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
y = [0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]x = [[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]]x = [[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1.

In [19]:
index = half = n_instances // 2
print(f"X[index] =\n{X[index]}")
print(f"Y[index] = {Y[index]}")

X[index] =
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Y[index] = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [20]:
index = -1
print(f"X[index] =\n{X[index]}")
print(f"Y[index] = {Y[index]}")

X[index] =
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Y[index] = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [21]:
index = 1
print(f"X[index] =\n{X[index]}")
print(f"Y[index] = {Y[index]}")

X[index] =
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
Y[index] = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


This multi-threaded code has bug -- I think it's because `X` and `Y` are not really getting updated. Besides, the length `10` task is heaviest, way heavier than length `<=7`, so rearrange the workload.

## Model